export const ADD_STUDENT_LOADING = 'ADD_STUDENT_LOADING'
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_ERROR = 'ADD_STUDENT_ERROR'

export const GET_STUDENT_LOADING = 'GET_STUDENT_LOADING'
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS'
export const GET_STUDENT_ERROR = 'GET_STUDENT_ERROR'



export const REMOVE_STUDENT = 'REMOVE_STUDENT'
export const GET_STUDENT = 'GET_STUDENT'
export const ADD_CONTEST = 'ADD_CONTEST'
export const REMOVE_CONTEST = 'REMOVE_CONTEST'